import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ibm_plex_sans } from "./fonts/app.font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ibm_plex_sans.className} antialiased`}>
        <AntdRegistry>
          {/* <Sidemenu> */}
            {children}
            {/* </Sidemenu> */}
        </AntdRegistry>
      </body>
    </html>
  );
}
